strains:
  proxy:
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  default:
    content: https://github.com/trieloff/helix-demo.git
    static: https://github.com/trieloff/helix-demo.git/htdocs
    code: ssh://git@github.com/trieloff/helix-demo.git#master
    package: trieloff/81c2a71791d322eea6df5aa9fd0162f81c2f9a79
  legacy:
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io
