strains:
  - name: proxy
    condition:
      url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  - name: default
    content: 'https://github.com/trieloff/helix-demo.git#master'
    static: https://github.com/trieloff/helix-demo.git/htdocs#master
    code: ssh://git@github.com/trieloff/helix-demo.git#master
    package: helix-mini/1c5a9c84c2f7ee6f674bdf13436a7d904f518cfd
  - name: legacy
    condition:
      url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io
