strains:
  proxy:
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  default:
    content: https://github.com/trieloff/helix-demo.git#master
    static: https://github.com/trieloff/helix-demo.git/htdocs#master
    code: ssh://git@github.com/trieloff/helix-demo.git#master
    package: trieloff/597558e2d463858925daf4c64fa118e44d941291
  legacy:
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io
