strains:
  - name: proxy
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  - name: default
    content: https://github.com/trieloff/helix-demo.git#master
    static: https://github.com/trieloff/helix-demo.git/htdocs#master
    code: ssh://git@github.com/trieloff/helix-demo.git#master
    package: trieloff/c6964d1f741701117695b014d90359e762523c2a
  - name: stage-legacy
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io

  - name: test
    code: ssh://git@github.com/trieloff/helix-demo.git#test-branch
    content: https://github.com/trieloff/helix-demo.git#master
    static: https://github.com/trieloff/helix-demo.git/htdocs#master
    package: trieloff/2c5fbf40237634b75ba3ed821172dfc53b27a091
