strains:
  - name: proxy
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  - name: default
    content: https://github.com/trieloff/helix-demo.git#master
    static: https://github.com/trieloff/helix-demo.git/htdocs#master
    code: ssh://git@github.com/trieloff/helix-demo.git#master
    package: trieloff/ad00653da30ffb29fca7e408e2d03a8d81305c6c
  - name: legacy
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io
