strains:
  proxy:
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  default:
    content: https://github.com/trieloff/helix-demo.git#master
    static: https://github.com/trieloff/helix-demo.git/htdocs#master
    code: ssh://git@github.com/trieloff/helix-demo.git#master
    package: trieloff/b3a1a6cff21f03ee6b9b3e8985111ddc945edb5c
  legacy:
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io
