strains:
  proxy:
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  default:
    content: https://github.com/trieloff/helix-demo.git#master
    static: https://github.com/trieloff/helix-demo.git/htdocs
    code: ssh://git@github.com/trieloff/helix-demo.git#master
    package: trieloff/3ee89b30f26f1b5d97e4209f0e4da7c27a9e9d73
  legacy:
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io
