strains:
  proxy:
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  default:
    content: https://github.com/trieloff/helix-demo.git
    static: https://github.com/trieloff/helix-demo.git
    code: https://github.com/trieloff/helix-demo.git
  legacy:
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io    